export const movies = [
    { id: 1, title: "The Shawshank Redemption", director: "Frank Darabont" },
    { id: 2, title: "The Godfather", director: "Francis Ford Copp" },
    { id: 3, title: "The Dark Knight", director: "Christopher Nolan" },
    { id: 4, title: "Pulp Fiction", director: "Quentin Tarantino" },
    { id: 5, title: "The Lord of the Rings: The Return of the King", director: "Peter Jackson" },
    { id: 6, title: "Forrest Gump", director: "Robert Zemeckis" },
    { id: 7, title: "Inception", director: "Christopher Nolan" },
    { id: 8, title: "Fight Club", director: "David Fincher" },
    { id: 9, title: "The Matrix", director: "Lana Wachowski, Lilly Wachowski" },
    { id: 10, title: "Goodfellas", director: "Martin Scorsese" },
    { id: 11, title: "Star Wars: Episode V - The Empire Strikes Back", director: "Irvin Kershner" },
    { id: 12, title: "The Silence of the Lambs", director: "Jonathan Demme" },
    { id: 13, title: "Saving Private Ryan", director: "Steven Spielberg" },
    { id: 14, title: "Schindler's List", director: "Steven Spielberg" },
    { id: 15, title: "The Green Mile", director: "Frank Darabont" },
    { id: 16, title: "Interstellar", director: "Christopher Nolan" },
    { id: 17, title: "Gladiator", director: "Ridley Scott" },
    { id: 18, title: "The Departed", director: "Martin Scorsese" },
    { id: 19, title: "The Prestige", director: "Christopher Nolan" },
    { id: 20, title: "The Lion King", director: "Roger Allers, Rob Minkoff" },
    { id: 21, title: "Django Unchained", director: "Quentin Tarantino" },
    { id: 22, title: "Braveheart", director: "Mel Gibson" },
    { id: 23, title: "The Avengers", director: "Joss Whedon" },
    { id: 24, title: "Parasite", director: "Bong Joon Ho" },
    { id: 25, title: "The Social Network", director: "David Fincher" }
  ];
  

export const products = [
  { id: 1, name: "Wireless Mouse", price: 19.99, category: "Electronics" },
  { id: 2, name: "Mechanical Keyboard", price: 89.99, category: "Electronics" },
  { id: 3, name: "Smartphone Case", price: 15.99, category: "Accessories" },
  { id: 4, name: "Noise-Cancelling Headphones", price: 199.99, category: "Electronics" },
  { id: 5, name: "Running Shoes", price: 59.99, category: "Footwear" },
  { id: 6, name: "Yoga Mat", price: 25.99, category: "Fitness" },
  { id: 7, name: "Water Bottle", price: 9.99, category: "Fitness" },
  { id: 8, name: "Laptop Stand", price: 34.99, category: "Office Supplies" },
  { id: 9, name: "Ergonomic Chair", price: 149.99, category: "Office Supplies" },
  { id: 10, name: "Desk Lamp", price: 39.99, category: "Office Supplies" },
  { id: 11, name: "Graphic T-Shirt", price: 19.99, category: "Clothing" },
  { id: 12, name: "Slim Fit Jeans", price: 49.99, category: "Clothing" },
  { id: 13, name: "Wireless Charger", price: 29.99, category: "Electronics" },
  { id: 14, name: "Smartwatch", price: 249.99, category: "Electronics" },
  { id: 15, name: "Bluetooth Speaker", price: 45.99, category: "Electronics" },
  { id: 16, name: "Electric Kettle", price: 24.99, category: "Kitchen Appliances" },
  { id: 17, name: "Non-Stick Frying Pan", price: 29.99, category: "Kitchen Appliances" },
  { id: 18, name: "Stainless Steel Knife Set", price: 89.99, category: "Kitchen Appliances" },
  { id: 19, name: "Foldable Treadmill", price: 499.99, category: "Fitness" },
  { id: 20, name: "Action Camera", price: 129.99, category: "Electronics" },
  { id: 21, name: "Hiking Backpack", price: 74.99, category: "Outdoor" },
  { id: 22, name: "Camping Tent", price: 129.99, category: "Outdoor" },
  { id: 23, name: "Portable Power Bank", price: 34.99, category: "Electronics" },
  { id: 24, name: "LED Fairy Lights", price: 12.99, category: "Home Decor" },
  { id: 25, name: "Digital Alarm Clock", price: 19.99, category: "Home Decor" },
];

export const library = [
  { id: 1, title: "To Kill a Mockingbird", author: "Harper Lee", rating: 4.8 },
  { id: 2, title: "1984", author: "George Orwell", rating: 4.7 },
  { id: 3, title: "The Great Gatsby", author: "F. Scott Fitzgerald", rating: 4.6 },
  { id: 4, title: "Pride and Prejudice", author: "Jane Austen", rating: 4.9 },
  { id: 5, title: "The Catcher in the Rye", author: "J.D. Salinger", rating: 4.3 },
  { id: 6, title: "Moby Dick", author: "Herman Melville", rating: 4.2 },
  { id: 7, title: "War and Peace", author: "Leo Tolstoy", rating: 4.5 },
  { id: 8, title: "The Hobbit", author: "J.R.R. Tolkien", rating: 4.8 },
  { id: 9, title: "Brave New World", author: "Aldous Huxley", rating: 4.4 },
  { id: 10, title: "Crime and Punishment", author: "Fyodor Dostoevsky", rating: 4.6 },
  { id: 11, title: "Jane Eyre", author: "Charlotte Bronte", rating: 4.7 },
  { id: 12, title: "The Odyssey", author: "Homer", rating: 4.3 },
  { id: 13, title: "Wuthering Heights", author: "Emily Bronte", rating: 4.5 },
  { id: 14, title: "Animal Farm", author: "George Orwell", rating: 4.6 },
  { id: 15, title: "The Alchemist", author: "Paulo Coelho", rating: 4.7 },
  { id: 16, title: "The Divine Comedy", author: "Dante Alighieri", rating: 4.4 },
  { id: 17, title: "Les Misérables", author: "Victor Hugo", rating: 4.6 },
  { id: 18, title: "Dracula", author: "Bram Stoker", rating: 4.3 },
  { id: 19, title: "Don Quixote", author: "Miguel de Cervantes", rating: 4.5 },
  { id: 20, title: "The Brothers Karamazov", author: "Fyodor Dostoevsky", rating: 4.8 },
  { id: 21, title: "The Little Prince", author: "Antoine de Saint-Exupéry", rating: 4.7 },
  { id: 22, title: "Frankenstein", author: "Mary Shelley", rating: 4.6 },
  { id: 23, title: "The Kite Runner", author: "Khaled Hosseini", rating: 4.8 },
  { id: 24, title: "The Road", author: "Cormac McCarthy", rating: 4.4 },
  { id: 25, title: "Harry Potter and the Sorcerer's Stone", author: "J.K. Rowling", rating: 4.9 },
  { id: 26, title: "The Hunger Games", author: "Suzanne Collins", rating: 4.6 },
  { id: 27, title: "Life of Pi", author: "Yann Martel", rating: 4.5 },
  { id: 28, title: "The Lord of the Rings", author: "J.R.R. Tolkien", rating: 4.9 },
  { id: 29, title: "Gone Girl", author: "Gillian Flynn", rating: 4.3 },
  { id: 30, title: "The Fault in Our Stars", author: "John Green", rating: 4.4 },
  { id: 31, title: "A Tale of Two Cities", author: "Charles Dickens", rating: 4.7 },
  { id: 32, title: "The Picture of Dorian Gray", author: "Oscar Wilde", rating: 4.6 },
  { id: 33, title: "Catch-22", author: "Joseph Heller", rating: 4.5 },
  { id: 34, title: "Slaughterhouse-Five", author: "Kurt Vonnegut", rating: 4.4 },
  { id: 35, title: "The Shining", author: "Stephen King", rating: 4.6 },
  { id: 36, title: "The Stand", author: "Stephen King", rating: 4.5 },
  { id: 37, title: "Dune", author: "Frank Herbert", rating: 4.8 },
  { id: 38, title: "Beloved", author: "Toni Morrison", rating: 4.6 },
  { id: 39, title: "The Giver", author: "Lois Lowry", rating: 4.4 },
  { id: 40, title: "The Color Purple", author: "Alice Walker", rating: 4.7 },
];